### ISSUE TITLE
Rearchitect this repo as GitHub pages

### ISSUE THREAD

**Issue by di** [di/pyreadiness#12]
Currently this is hosted on Google Cloud Storage, with the function on Cloud Functions occasionally being run by Cloud Scheduler.

I'd like to update this so that the site is entirely hosted via GitHub pages, with a GitHub action running running on a cron and pushing changes to this repo. This would simplify 'deployment' for me, make it easier to track changes as they happen, and ensure this service remains long-term.

@hugovk, would you be interested in working on that?

**Comment by hugovk** [comment]
Good idea! Sure, I'll look into it.

**Comment by di** [comment]
This is halfway done with 76bf67823534a5b795d67112740437415abd0380: the repo is configured to serve `/docs` at http://test.pyreadiness.org/ (for now) and the script has been modified to write the files locally when run directly.

Next steps would be creating the action that writes these and commits them back to the repo.

**Comment by di** [comment]
I added the workflow in 1a7177dda7c480249520e1ab3d89adb002500ce6, this should run daily and update the repo.

Will leave this open until I can confirm that that's working and have updated the domain.

**Comment by di** [comment]
This is done!

**Comment by hugovk** [comment]
Good stuff! 🚀
