### ISSUE TITLE
Packages incorrectly reported as not compatible

### ISSUE THREAD

**Issue by ljden** [di/pyreadiness#32]
pyreadiness says flask, Jinja2, Werkzeug are not compatible with python 3.7-3.10. This is incorrect and the pypi listing says they are compatible with >= 3.7
These are just a few I knew were wrong, there could be others. 
psutils should also be compatible as it requires >=2.7 if != 3.0.-3.3.*

**Comment by di** [comment]
Duplicate of #18.
