### ISSUE TITLE
About „white“ packages

### ISSUE THREAD

**Issue by homeworkprod** [di/pyreadiness#65]
The site mentions „green“ and „white“ packages. But when browsing in dark mode, the white packages are no longer white but instead in a very dark gray (or even black, didn‘t check).

Since forcing a white background in dark mode would likely be a bit uncomfortable for the reader, how about adjusting the wording? Ideas welcome.

**Comment by hugovk** [comment]
Good point, for https://hugovk.github.io/free-threaded-wheels/ we changed it to "uncolored".

Would you like to open a PR to update the wording?
