### ISSUE TITLE
No packages on 3.9 page

### ISSUE THREAD

**Issue by gricey432** [di/pyreadiness#9]
https://pyreadiness.org/3.9/ doesn't list any packages at all for me

**Comment by gricey432** [comment]
Actually now I check, it seems to be all the pages

**Comment by di** [comment]
Thanks for the report! Should be resolved now, but please feel free to let me know if you see it again.

Also, if you have a moment to tell me where you found this site and what you're using it for, I'd appreciate it!

**Comment by gricey432** [comment]
It's the first result on https://duckduckgo.com/?q=python+3.9+support&ia=web and was using it to check if all the libraries I use would be able to run on 3.9
